[package]
name = "dowel_parser"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "TSX analysis and Style IR construction."

[dependencies]
dowel_ir = { path = "../dowel_ir" }
oxc_allocator = "0.144.0"
oxc_ast = "0.144.0"
oxc_ast_visit = "0.144.0"
oxc_parser = "0.144.0"
oxc_span = "0.144.0"
oxc_syntax = "0.144.0"
