[package]
name = "dowel_napi"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Node native binding exposing the Dowel compiler to JS build tooling."

[lib]
crate-type = ["cdylib"]

[dependencies]
dowel_ir = { path = "../dowel_ir" }
dowel_native = { version = "0.0.0", path = "../dowel_native" }
dowel_parser = { path = "../dowel_parser" }
dowel_web = { path = "../dowel_web" }
napi = "3.12.1"
napi-derive = "3.6.3"

[build-dependencies]
napi-build = "2.4.1"
