import assert from 'node:assert/strict'
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'
import test from 'node:test'

import { metroStatePath, withHozo } from './config.ts'

test('withHozo preserves Metro settings and records the existing transformer', async () => {
  const root = mkdtempSync(path.join(tmpdir(), 'hozo-metro-config-'))
  try {
    mkdirSync(path.join(root, 'src'))
    writeFileSync(
      path.join(root, 'src', 'App.tsx'),
      `import { View } from '@hozo/core'\nexport const App = () => <View className="p-4" />\n`,
    )
    const upstream = path.join(root, 'custom-transformer.cjs')
    const config = {
      projectRoot: root,
      resolver: { sourceExts: ['js', 'tsx'] },
      transformer: { babelTransformerPath: upstream, minifierPath: 'keep-me' },
    }

    const result = await withHozo(config)

    assert.notEqual(result, config)
    assert.deepEqual(result.resolver, config.resolver)
    assert.equal(result.transformer.minifierPath, 'keep-me')
    assert.match(result.transformer.babelTransformerPath, /packages[\\/]metro[\\/]src[\\/]index\.ts$/)
    assert.deepEqual(JSON.parse(readFileSync(metroStatePath(root), 'utf8')), {
      upstreamTransformer: upstream,
    })
    assert.match(
      readFileSync(path.join(root, 'node_modules', '.hozo', 'candidates.native.js'), 'utf8'),
      /Generated by Hozo/,
    )
  } finally {
    rmSync(root, { recursive: true, force: true })
  }
})

test('withHozo accepts a promised config and an explicit project root', async () => {
  const root = mkdtempSync(path.join(tmpdir(), 'hozo-metro-promise-'))
  try {
    const result = await withHozo(Promise.resolve({ transformer: {} }), {
      projectRoot: root,
      css: 'styles/tailwind.css',
      content: { include: [] },
    })

    assert.match(result.transformer.babelTransformerPath, /index\.ts$/)
    assert.deepEqual(JSON.parse(readFileSync(metroStatePath(root), 'utf8')), {
      css: 'styles/tailwind.css',
    })
  } finally {
    rmSync(root, { recursive: true, force: true })
  }
})
