// Generated by scripts/generate-aria.mjs from aria-query. Do not edit.
//
// The ARIA specification, as a table: which roles exist, and what each one
// requires to mean anything. Derived rather than chosen -- the same move
// the Tailwind harness makes by asking Tailwind for its own class list,
// and for the same reason: a hand-kept copy of somebody else's
// specification drifts, and both halves go on looking reasonable while it
// does.
//
// Roles from the DPUB and Graphics modules are left out. They are separate
// specifications with their own host languages, and nothing in Hozo can
// say anything useful about them yet.

pub struct AriaRole {
    pub name: &'static str,
    /// Part of ARIA's ontology rather than something to write.
    ///
    /// The specification is explicit that authors must not use an abstract
    /// role. They are in the table because `role="widget"` deserves a
    /// better answer than "not a role": it is a real name, used wrongly.
    pub is_abstract: bool,
    /// States and properties the role is meaningless without.
    pub required_props: &'static [&'static str],
    /// Roles this one must be contained by.
    pub required_context: &'static [&'static str],
    /// Roles this one must contain.
    pub required_owned: &'static [&'static str],
}

pub const ARIA_ROLES: &[AriaRole] = &[
    AriaRole { name: "alert", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "alertdialog", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "application", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "article", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "banner", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "blockquote", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "button", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "caption", is_abstract: false, required_props: &[], required_context: &["figure", "grid", "table"], required_owned: &[] },
    AriaRole { name: "cell", is_abstract: false, required_props: &[], required_context: &["row"], required_owned: &[] },
    AriaRole { name: "checkbox", is_abstract: false, required_props: &["aria-checked"], required_context: &[], required_owned: &[] },
    AriaRole { name: "code", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "columnheader", is_abstract: false, required_props: &[], required_context: &["row"], required_owned: &[] },
    AriaRole { name: "combobox", is_abstract: false, required_props: &["aria-controls", "aria-expanded"], required_context: &[], required_owned: &[] },
    AriaRole { name: "command", is_abstract: true, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "complementary", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "composite", is_abstract: true, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "contentinfo", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "definition", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "deletion", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "dialog", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "directory", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "document", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "emphasis", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "feed", is_abstract: false, required_props: &[], required_context: &[], required_owned: &["article"] },
    AriaRole { name: "figure", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "form", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "generic", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "grid", is_abstract: false, required_props: &[], required_context: &[], required_owned: &["row"] },
    AriaRole { name: "gridcell", is_abstract: false, required_props: &[], required_context: &["row"], required_owned: &[] },
    AriaRole { name: "group", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "heading", is_abstract: false, required_props: &["aria-level"], required_context: &[], required_owned: &[] },
    AriaRole { name: "img", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "input", is_abstract: true, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "insertion", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "landmark", is_abstract: true, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "link", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "list", is_abstract: false, required_props: &[], required_context: &[], required_owned: &["listitem"] },
    AriaRole { name: "listbox", is_abstract: false, required_props: &[], required_context: &[], required_owned: &["option"] },
    AriaRole { name: "listitem", is_abstract: false, required_props: &[], required_context: &["directory", "list"], required_owned: &[] },
    AriaRole { name: "log", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "main", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "mark", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "marquee", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "math", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "menu", is_abstract: false, required_props: &[], required_context: &[], required_owned: &["menuitem", "menuitemcheckbox", "menuitemradio"] },
    AriaRole { name: "menubar", is_abstract: false, required_props: &[], required_context: &[], required_owned: &["menuitem", "menuitemcheckbox", "menuitemradio"] },
    AriaRole { name: "menuitem", is_abstract: false, required_props: &[], required_context: &["group", "menu", "menubar"], required_owned: &[] },
    AriaRole { name: "menuitemcheckbox", is_abstract: false, required_props: &["aria-checked"], required_context: &["group", "menu", "menubar"], required_owned: &[] },
    AriaRole { name: "menuitemradio", is_abstract: false, required_props: &["aria-checked"], required_context: &["group", "menu", "menubar"], required_owned: &[] },
    AriaRole { name: "meter", is_abstract: false, required_props: &["aria-valuenow"], required_context: &[], required_owned: &[] },
    AriaRole { name: "navigation", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "none", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "note", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "option", is_abstract: false, required_props: &["aria-selected"], required_context: &[], required_owned: &[] },
    AriaRole { name: "paragraph", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "presentation", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "progressbar", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "radio", is_abstract: false, required_props: &["aria-checked"], required_context: &[], required_owned: &[] },
    AriaRole { name: "radiogroup", is_abstract: false, required_props: &[], required_context: &[], required_owned: &["radio"] },
    AriaRole { name: "range", is_abstract: true, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "region", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "roletype", is_abstract: true, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "row", is_abstract: false, required_props: &[], required_context: &["grid", "rowgroup", "table", "treegrid"], required_owned: &["cell", "columnheader", "gridcell", "rowheader"] },
    AriaRole { name: "rowgroup", is_abstract: false, required_props: &[], required_context: &["grid", "table", "treegrid"], required_owned: &["row"] },
    AriaRole { name: "rowheader", is_abstract: false, required_props: &[], required_context: &["row", "rowgroup"], required_owned: &[] },
    AriaRole { name: "scrollbar", is_abstract: false, required_props: &["aria-controls", "aria-valuenow"], required_context: &[], required_owned: &[] },
    AriaRole { name: "search", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "searchbox", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "section", is_abstract: true, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "sectionhead", is_abstract: true, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "select", is_abstract: true, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "separator", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "slider", is_abstract: false, required_props: &["aria-valuenow"], required_context: &[], required_owned: &[] },
    AriaRole { name: "spinbutton", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "status", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "strong", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "structure", is_abstract: true, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "subscript", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "superscript", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "switch", is_abstract: false, required_props: &["aria-checked"], required_context: &[], required_owned: &[] },
    AriaRole { name: "tab", is_abstract: false, required_props: &[], required_context: &["tablist"], required_owned: &[] },
    AriaRole { name: "table", is_abstract: false, required_props: &[], required_context: &[], required_owned: &["row"] },
    AriaRole { name: "tablist", is_abstract: false, required_props: &[], required_context: &[], required_owned: &["tab"] },
    AriaRole { name: "tabpanel", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "term", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "textbox", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "time", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "timer", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "toolbar", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "tooltip", is_abstract: false, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "tree", is_abstract: false, required_props: &[], required_context: &[], required_owned: &["treeitem"] },
    AriaRole { name: "treegrid", is_abstract: false, required_props: &[], required_context: &[], required_owned: &["row"] },
    AriaRole { name: "treeitem", is_abstract: false, required_props: &["aria-selected"], required_context: &["group", "tree"], required_owned: &[] },
    AriaRole { name: "widget", is_abstract: true, required_props: &[], required_context: &[], required_owned: &[] },
    AriaRole { name: "window", is_abstract: true, required_props: &[], required_context: &[], required_owned: &[] },
];

/// Whether `name` is a role an author may write.
///
/// Abstract roles are excluded: they describe the ontology, and the
/// specification forbids writing them.
pub fn is_role(name: &str) -> bool {
    ARIA_ROLES.iter().any(|role| role.name == name && !role.is_abstract)
}

/// Whether `name` is one of ARIA's abstract roles.
pub fn is_abstract_role(name: &str) -> bool {
    ARIA_ROLES.iter().any(|role| role.name == name && role.is_abstract)
}

/// The specification's entry for `name`.
pub fn role(name: &str) -> Option<&'static AriaRole> {
    ARIA_ROLES.iter().find(|role| role.name == name)
}
