// Generated by scripts/generate-tailwind-variants.mjs from tailwindcss. Do not edit.
//
// Every variant name Tailwind defines. Hozo implements a fraction of them,
// and this is what lets it tell the difference between a class it should
// have compiled and one that was never Tailwind's to begin with -- a
// project's own `my-card` is not a gap in Hozo, and `group-hover:` is.
//
// Names only. What each variant *means* is Tailwind's business and, where
// Hozo implements one, `tailwind.rs`'s.

/// Every variant name Tailwind defines, sorted.
pub const TAILWIND_VARIANTS: &[&str] = &[
    "*",
    "**",
    "@",
    "@max",
    "@min",
    "active",
    "after",
    "any-pointer-coarse",
    "any-pointer-fine",
    "any-pointer-none",
    "aria",
    "autofill",
    "backdrop",
    "before",
    "checked",
    "contrast-less",
    "contrast-more",
    "dark",
    "data",
    "default",
    "details-content",
    "disabled",
    "empty",
    "enabled",
    "even",
    "file",
    "first",
    "first-letter",
    "first-line",
    "first-of-type",
    "focus",
    "focus-visible",
    "focus-within",
    "forced-colors",
    "group",
    "has",
    "hover",
    "in",
    "in-range",
    "indeterminate",
    "inert",
    "invalid",
    "inverted-colors",
    "landscape",
    "last",
    "last-of-type",
    "ltr",
    "marker",
    "max",
    "min",
    "motion-reduce",
    "motion-safe",
    "noscript",
    "not",
    "nth",
    "nth-last",
    "nth-last-of-type",
    "nth-of-type",
    "odd",
    "only",
    "only-of-type",
    "open",
    "optional",
    "out-of-range",
    "peer",
    "placeholder",
    "placeholder-shown",
    "pointer-coarse",
    "pointer-fine",
    "pointer-none",
    "portrait",
    "print",
    "read-only",
    "required",
    "rtl",
    "selection",
    "starting",
    "supports",
    "target",
    "user-invalid",
    "user-valid",
    "valid",
    "visited",
];

/// Whether `name` is a variant Tailwind defines.
///
/// Functional variants (`aria`, `data`, `group`, `peer`, `has`, `not`,
/// `supports`, `min`, `max`) are listed under their bare name and written
/// with a suffix or an argument -- `aria-checked:`, `group-hover:`. So a
/// prefix is checked whole and then again up to its first dash.
pub fn is_variant(name: &str) -> bool {
    if TAILWIND_VARIANTS.contains(&name) {
        return true;
    }
    match name.split_once('-') {
        Some((head, _)) => TAILWIND_VARIANTS.contains(&head),
        None => false,
    }
}
